# Site settings
author: Elizabeth Mangus
title: 
header-img: img/home-bg.png
email: lizmangus@ymail.com
copyright_name: Elizabeth Mangus
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  lizmangus

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
